name: python-app quality-assurance

on:
  pull_request:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  qa:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout python-app
        uses: actions/checkout@v4
        with:
          path: python-app

# Instead of setup Python and pip install there should be Docker container pulled with preinstalled deps
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install qa deps
        run: |
          ls -lah
          pip install -r requirements-dev.txt

      - name: Run app tests
        run: |
          tox